version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_DATASOURCE_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_PORT:$DOCKER_MYSQL_PORT
    expose:
      - $MYSQL_PORT

  online-book-store:
    restart: on-failure
    build: .
    container_name: online-book-store
    env_file: ./.env
    environment:
      - spring.datasource.url=$MYSQL_DATASOURCE_URL
      - spring.datasource.username=$MYSQL_DATASOURCE_USERNAME
      - spring.datasource.password=$MYSQL_DATASOURCE_PASSWORD
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    depends_on:
      - db

